__all__ = [
    "HIDDEN_DIM",
    "BATCH",
    "LEARNING_RATE",
    "EMA_PARAM",
    "NUM_EPOCHS",
    "MASK_RATIO",
    "T_TEACHER",
    "T_STUDENT",
    "VICREG_WEIGHT",
    "VICREG_VAR_WEIGHT", 
    "VICREG_COV_WEIGHT",
    "VICREG_GAMMA"
]

HIDDEN_DIM = 768
BATCH = 16
LEARNING_RATE = 1e-4
EMA_PARAM = 0.996
NUM_EPOCHS = 10
MASK_RATIO = 0.45
T_TEACHER = 0.04
T_STUDENT = 0.1

VICREG_VAR_WEIGHT = 1.0
VICREG_COV_WEIGHT = 0.05
VICREG_GAMMA = 1.0