__all__ = [
    "HIDDEN_DIM",
    "BATCH",
    "LEARNING_RATE",
    "EMA_PARAM",
    "NUM_EPOCHS",
    "MASK_RATIO",
    "T_TEACHER",
    "T_STUDENT",
    "ACCUMULATION_STEPS",
    "VICREG_VAR_WEIGHT", 
    "VICREG_COV_WEIGHT",
    "VICREG_GAMMA",
    "K_NEIGHBOR"
]

HIDDEN_DIM = 768
BATCH = 1
ACCUMULATION_STEPS = 32
LEARNING_RATE = 1e-4
EMA_PARAM = 0.995
NUM_EPOCHS = 15
MASK_RATIO = 0.30
T_TEACHER = 0.07
T_STUDENT = 0.1
K_NEIGHBOR = 64

VICREG_VAR_WEIGHT = 1.0
VICREG_COV_WEIGHT = 0.07
VICREG_GAMMA = 0.5